[package]
name = "svix-server_derive"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.15"
syn = { version = "2.0.48", features = ["full"] }

[lints]
workspace = true
