[workspace]
members = ["svix-server", "svix-server_derive"]
resolver = "2"

[workspace.lints.rust]
rust_2018_idioms = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"

[workspace.lints.clippy]
cloned_instead_of_copied = "warn"
dbg_macro = "warn"
inefficient_to_string = "warn"
macro_use_imports = "warn"
mut_mut = "warn"
nonstandard_macro_braces = "warn"
todo = "warn"
uninlined_format_args = "warn"

[profile.dev.package]
quote = { opt-level = 2 }

[patch.crates-io]
hyper = { git = "https://github.com/svix/hyper/", rev = "63efac5a6719937359d61a1bb1b93d9ce88f0e3d" }
