version: "3.7"
services:
  backend:
    environment:
      SVIX_JWT_SECRET: "x"
  pgbouncer:
    ports:
      - "8079:5432" # Needed for sqlx
  redis:
    ports:
      - "8078:6379" # Needed for sqlx
