name: C# Lint

on:
  pull_request:
    paths:
      - "csharp/**"
      - "openapi.json"
      - '.github/workflows/csharp-lint.yml'

jobs:
  dotnet:
    name: C# Lint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Regen openapi libs
        run: |
          yarn
          ./regen_openapi.sh

      - name: Install dependencies
        run: |
          cd csharp
          dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./csharp

      - name: Test
        run: dotnet test Svix.Tests
        working-directory: ./csharp
