name: C# Release

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Mega Releaser
    types:
      - completed

jobs:
  dotnet:
    name: C# Release
    runs-on: ubuntu-24.04
    environment: release

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: |
          cd csharp
          dotnet restore

      - name: Build
        run: |
          cd csharp
          dotnet build --configuration Release Svix --no-restore

      - name: Release
        run: |
          cd csharp
          dotnet nuget push "$(find Svix/bin/Release/Svix.*.nupkg)" \
            --api-key "$NUGET_API_KEY" \
            --source "https://api.nuget.org/v3/index.json"
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
