name: JavaScript Release

on:
  push:
    branches:
      - main
    paths:
      - 'lib-openapi.json'
      - 'javascript/**'
      - '.github/workflows/javascript-release.yml'
  workflow_dispatch:
  workflow_run:
    workflows:
      - Mega Releaser
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: release

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'

      - name: Install modules and update NPM
        run: |
          cd javascript
          npm install -g npm@latest
          npm install

      - name: Publish
        if: ${{ github.ref_type == 'tag' || startsWith(github.event.workflow_run.head_branch,'v') }}
        run: |
          npm publish
