name: Kotlin Release

on:
  push:
    tags:
      - 'v*'

jobs:
  kotlin:
    name: Kotlin Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Regen openapi libs
        run: |
          yarn
          ./regen_openapi.sh

      - name: Restore gradle.properties
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> "$GITHUB_ENV"

          {
            echo "NEXUS_USERNAME=$NEXUS_USERNAME"
            echo "NEXUS_PASSWORD=$NEXUS_PASSWORD"
            echo "signing.gnupg.keyName=$OSSRH_GPG_KEY_NAME"
            echo "signing.gnupg.passphrase=$OSSRH_GPG_SECRET_KEY_PASSWORD"
          } >> ~/.gradle/gradle.properties
        env:
          NEXUS_USERNAME: "${{secrets.NEXUS_USERNAME}}"
          NEXUS_PASSWORD: "${{secrets.NEXUS_PASSWORD}}"
          OSSRH_GPG_KEY_NAME: "${{secrets.OSSRH_GPG_KEY_NAME}}"
          OSSRH_GPG_SECRET_KEY_PASSWORD: "${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}"

      - name: Install GPG Signing Key
        run: |
          echo -e "$OSSRH_GPG_SECRET_KEY" | gpg --batch --import
        env:
          OSSRH_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
  
      - name: Publish
        run: |
          cd kotlin
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
