name: PHP CI

on:
  push:
    branches:
      - main
    paths:
      - "php/**"
      - ".github/workflows/php-ci.yml"
  pull_request:
    paths:
      - "php/**"
      - ".github/workflows/php-ci.yml"
jobs:
  build-test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        with:
          version: latest
          configuration: "php/phpunit.xml"
          test_suffix: "Test.php"
