name: Python Tests
on:
  push:
    branches:
      - main
    paths:
      - "python/**"
      - "codegen/lib-openapi.json"
      - "server/**"
      - ".github/workflows/python-tests.yml"
  pull_request:
    paths:
      - "python/**"
      - "codegen/lib-openapi.json"
      - "server/**"
      - ".github/workflows/python-tests.yml"
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Pull svix server image (and dependencies)
        run: docker compose pull
        working-directory: ./server

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt .
          python -m pip install -r requirements-dev.txt .
        working-directory: ./python

      - name: Check typing on client tests
        run: mypy tests/test_client.py
        working-directory: ./python

      - name: Run Python tests
        run: pytest -sv
        working-directory: ./python
