name: Server Release

on:
  push:
    branches:
      - tom/arm64

jobs:
  docker:
    name: release docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Derive Version Numbers
        run: |
          export REPO="${{ secrets.DOCKERHUB_USERNAME }}/svix-server"
          echo DOCKER_TAGS="$(echo "${{ github.event.release.tag_name }}" | sed -E "s#v([0-9]+)\.([0-9]+)\.([0-9]+)#${REPO}:latest,${REPO}:v\1.\2.\3,${REPO}:v\1.\2,${REPO}:v\1#")" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          tags: ${{ env.DOCKER_TAGS }}
          platforms: linux/amd64,linux/arm64
